// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for VideoStatus.
const (
	Failed     VideoStatus = "failed"
	Pending    VideoStatus = "pending"
	Processing VideoStatus = "processing"
	Ready      VideoStatus = "ready"
	Uploaded   VideoStatus = "uploaded"
)

// Valid indicates whether the value is a known member of the VideoStatus enum.
func (e VideoStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Processing:
		return true
	case Ready:
		return true
	case Uploaded:
		return true
	default:
		return false
	}
}

// CreateVideoRequest defines model for CreateVideoRequest.
type CreateVideoRequest struct {
	// ContentType MIME type of the upload; defaults to application/octet-stream.
	ContentType *string `json:"content_type,omitempty"`

	// Filename Original filename, used to derive the storage object key.
	Filename string `json:"filename"`
	Title    string `json:"title"`
}

// CreateVideoResponse defines model for CreateVideoResponse.
type CreateVideoResponse struct {
	// ExpiresIn Seconds until the presigned URL expires.
	ExpiresIn int `json:"expires_in"`

	// UploadUrl Presigned PUT URL. Upload the raw file here.
	UploadUrl string `json:"upload_url"`
	Video     Video  `json:"video"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Video defines model for Video.
type Video struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// ObjectKey Key of the raw upload in the videos bucket.
	ObjectKey string      `json:"object_key"`
	Status    VideoStatus `json:"status"`
	Title     string      `json:"title"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// VideoStatus defines model for VideoStatus.
type VideoStatus string

// VideoId defines model for VideoId.
type VideoId = openapi_types.UUID

// CreateVideoJSONRequestBody defines body for CreateVideo for application/json ContentType.
type CreateVideoJSONRequestBody = CreateVideoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List videos
	// (GET /videos)
	ListVideos(w http.ResponseWriter, r *http.Request)
	// Initialize an upload and get a presigned PUT URL
	// (POST /videos)
	CreateVideo(w http.ResponseWriter, r *http.Request)
	// Get a single video
	// (GET /videos/{id})
	GetVideo(w http.ResponseWriter, r *http.Request, id VideoId)
	// Mark the upload finished and enqueue transcoding
	// (POST /videos/{id}/complete)
	CompleteVideo(w http.ResponseWriter, r *http.Request, id VideoId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListVideos operation middleware
func (siw *ServerInterfaceWrapper) ListVideos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVideos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVideo operation middleware
func (siw *ServerInterfaceWrapper) CreateVideo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVideo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVideo operation middleware
func (siw *ServerInterfaceWrapper) GetVideo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VideoId

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteVideo operation middleware
func (siw *ServerInterfaceWrapper) CompleteVideo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VideoId

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteVideo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/videos", wrapper.ListVideos).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/videos", wrapper.CreateVideo).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/videos/{id}", wrapper.GetVideo).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/videos/{id}/complete", wrapper.CompleteVideo).Methods(http.MethodPost)

	return r
}

type ErrorJSONResponse Error

type ListVideosRequestObject struct {
}

type ListVideosResponseObject interface {
	VisitListVideosResponse(w http.ResponseWriter) error
}

type ListVideos200JSONResponse []Video

func (response ListVideos200JSONResponse) VisitListVideosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVideoRequestObject struct {
	Body *CreateVideoJSONRequestBody
}

type CreateVideoResponseObject interface {
	VisitCreateVideoResponse(w http.ResponseWriter) error
}

type CreateVideo201JSONResponse CreateVideoResponse

func (response CreateVideo201JSONResponse) VisitCreateVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVideo400JSONResponse struct{ ErrorJSONResponse }

func (response CreateVideo400JSONResponse) VisitCreateVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetVideoRequestObject struct {
	Id VideoId `json:"id"`
}

type GetVideoResponseObject interface {
	VisitGetVideoResponse(w http.ResponseWriter) error
}

type GetVideo200JSONResponse Video

func (response GetVideo200JSONResponse) VisitGetVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVideo404JSONResponse struct{ ErrorJSONResponse }

func (response GetVideo404JSONResponse) VisitGetVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteVideoRequestObject struct {
	Id VideoId `json:"id"`
}

type CompleteVideoResponseObject interface {
	VisitCompleteVideoResponse(w http.ResponseWriter) error
}

type CompleteVideo200JSONResponse Video

func (response CompleteVideo200JSONResponse) VisitCompleteVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteVideo404JSONResponse struct{ ErrorJSONResponse }

func (response CompleteVideo404JSONResponse) VisitCompleteVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List videos
	// (GET /videos)
	ListVideos(ctx context.Context, request ListVideosRequestObject) (ListVideosResponseObject, error)
	// Initialize an upload and get a presigned PUT URL
	// (POST /videos)
	CreateVideo(ctx context.Context, request CreateVideoRequestObject) (CreateVideoResponseObject, error)
	// Get a single video
	// (GET /videos/{id})
	GetVideo(ctx context.Context, request GetVideoRequestObject) (GetVideoResponseObject, error)
	// Mark the upload finished and enqueue transcoding
	// (POST /videos/{id}/complete)
	CompleteVideo(ctx context.Context, request CompleteVideoRequestObject) (CompleteVideoResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListVideos operation middleware
func (sh *strictHandler) ListVideos(w http.ResponseWriter, r *http.Request) {
	var request ListVideosRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVideos(ctx, request.(ListVideosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVideos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVideosResponseObject); ok {
		if err := validResponse.VisitListVideosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVideo operation middleware
func (sh *strictHandler) CreateVideo(w http.ResponseWriter, r *http.Request) {
	var request CreateVideoRequestObject

	var body CreateVideoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVideo(ctx, request.(CreateVideoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVideo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVideoResponseObject); ok {
		if err := validResponse.VisitCreateVideoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVideo operation middleware
func (sh *strictHandler) GetVideo(w http.ResponseWriter, r *http.Request, id VideoId) {
	var request GetVideoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVideo(ctx, request.(GetVideoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVideo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVideoResponseObject); ok {
		if err := validResponse.VisitGetVideoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteVideo operation middleware
func (sh *strictHandler) CompleteVideo(w http.ResponseWriter, r *http.Request, id VideoId) {
	var request CompleteVideoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteVideo(ctx, request.(CompleteVideoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteVideo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteVideoResponseObject); ok {
		if err := validResponse.VisitCompleteVideoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FdNc9s2EP0rGLRHhlKaHDLqKW3T1NN44ollX1KPDRMrCTYIwMDSierRf+8sAFKkSDdO0x56o0js13v7",
	"dqEHXtnaWQMGA188cCe8qAHBx1/nSoI9kvSoDF9wJ3DDC25EDXzBleQF93DXKA+SL9A3UPBQbaAWZLGy",
	"vhbIF7xp4kncOrIK6JVZ891uR8bBWRMgBnvjvfX0UFmDYJAehXNaVQKVNbObYA2920f43sOKL/h3s30N",
	"s/Q1zJK3GEVCqLxy5IQvUhjWRuZ0INuQy589CIRY9we4ayDENJy3DjyqlGjO7zIV9HDg//jo+A2jT8yu",
	"GG6ANU5bIX9kElai0RgYWtavy1YI+CygB1GXvODwWdROE1T3lMasdi/H6BV8pTQkIg4zeO/VWhmhWXuk",
	"YE0ASXEleHUPMa2A1os1MHt9AxWyW9gOg2+sVlJsy0fCo0IdY+8tjrcsG7FKKzdBeb9dPmYXvUouOouU",
	"FMUZEJI5GzECn53yEC6VGaNxCpU1MrDGoNKxcuchqLUByc4+vGPZttynqwzCGjxFT9xdNl6PHZ90bk7O",
	"luSqZGfxeAzixaeIP9uAh3IKwcjul9o4Fj5CLpkO0iv6IEwB2clrCF0NIYh1xPTv2WoPTvk+b0s5EErk",
	"Tl4KHMwDKRCeoaphChUlnzA7ihz78ha2Y2J+h22rPWIhgcSUiW8idIFdN9Ut4CQvAQU24UnEnKajfTmM",
	"3DVOfiUIB8AnALJWcnIDAIo+0IOAj3J12tUIpqkpigMjKXrbVEBRnbcVhJDeexCSgq2E0iB7vvsTXZmV",
	"HTMSY7ZECCNZmnbKrNnrk6NWN4HGVE+dWVaBBUsDheBnAYxk11uEwKTyUKHe0lzLQyzPtLIDbMF/tX4N",
	"7Pz9LxSJF/wefEhJzcvn5Tz2kgMjnOIL/qKcly+oboGbiM4stQs9riESSP0d5zatRf5OBTxPRw622Q/z",
	"+VftMoVQhydOgw554b3YTi2510yrgKSCXEBcc01dC7/NabdfCo5iHbqpEvjFruDOpsU39JpmcWAi2TIP",
	"lfVRWVe5fa4YNShEjj1g4w2dHgzcki03kPnMLRGGE/NxYtknhRsmDPttuTyJ/YGWXe2n4FVBngyrhNbJ",
	"KYGoAYGBkc4qg+UfhhcHLPZ2TL7RQMCfrNz+a7eRiWvFbqhzuj3tRj30/L/JoLv7jBrnrB2WCpXQ6k+Q",
	"1G4vUzNP+e8S7m5c/UY76vwQa70BsAYcNEbW+lQ37opWhrMHJXePavEtYEth/xb7cTrv/ZFZe8vdXXyj",
	"hp+yyEeIL9ullIB++c+AfhvxpEmtW3dfhnLWqiOu7mnJC62ZWCH4KKcJybHQVBWADCVbemGCIsuw37W9",
	"8yCvIvlg7hpo4iBBMqmsBHZjr5lNO/oDSBXyjpjUa077/0h3FliLfFID1Z5Bkd/UBsfC3/b+dLCVMips",
	"cpQcocM8rfVxk5BH8PctnMP839lKaCbhHrR1NeFU8Hg95htEt5jNNB3Y2ICLV/NXc7672P0VAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
